package resource;

public enum TennisGameResource {
	PLAYER_CAN_NOT_BE_NULL,
	CAN_NOT_ADD_TWO_PLAYER_WITH_THE_SAME_NAME,
	YOU_SHOULD_ADD_TWO_PAYER_TO_START_THE_GAME,
	YOU_CAN_NOT_ADD_MORE_THAN_TWO_PLAYER,
	GAME_IS_OVER

}
